### ISSUE TITLE
timeout while waiting for angular

### ISSUE THREAD

**Issue by mbajur** [wrozka/capybara-angular#11]
Hello!
I'm trying to create a basic feature spec using capybara / rspec / angular but i'm not able to make my code working.

```
require 'rails_helper'

feature "Jobs Management", :type => :feature, current: true do
  include Capybara::Angular::DSL

  scenario 'SA creates a new Job' do
    Capybara.current_driver = :webkit

    visit '/#/users/sign_in'
    fill_in 'field-email', with: 'email@email.com'
    fill_in 'field-password', with: 'TestPass'
    click_button 'Sign in'
  end

end
```

The following spec throws `timeout while waiting for angular` exception. Am i doing something wrong? Thanks in advance for any clues

My env:
ruby 2
rails 4.1.0
rspec 3

**Comment by nhodges** [comment]
Fix works and resolves a lot of pain points in regards to tests running in a continuous integration setup. Great work @wrozka and @atermenji!

**Comment by casertap** [comment]
Bug has been reintroduce in 0.1.1 downgrade to 0.1.0 to fixe it.

**Comment by jhubbardsf** [comment]
Yup, bug is back and I even downgrading doesn't fix it for my application.

**Comment by ryaz** [comment]
Any update on that? I have the same issue in chrome but with poltergeist it works fine.

**Comment by KrDenis** [comment]
This help me

/rails_helper.rb
Capybara.configure do |config|
  config.default_wait_time = 5
end

**Comment by gumatias** [comment]
A not-so-obvious side note from me that might be relevant to others: these timeouts _might_ have to do more with how the app is performing than Capybara itself. Assuming there's a `default_max_wait_time` set, if your app continues querying for longer than that, it will certainly timeout. Check your logs while the specs are running.
