### ISSUE TITLE
Does nothing when using PhantomJS/Poltergeist

### ISSUE THREAD

**Issue by AntonTrapp** [wrozka/capybara-angular#14]
Adding the gem and adding include Capybara::Angular::DSL does nothing at all. With or without it a random number of tests is failing depending on how fast AngularJS is building the screen.

Strange thing: using 0.0.4 - tried "ng-app" instead of "data-ng-app". Working. Looked at the code "[ng-app], [data-ng-app]" - so why I can use it with ng-app and why it completely ignores data-ng-app? *LOL*???

**Comment by gsands** [comment]
Easy!  From the project readme:
Limitations
At the moment it works with AngularJS applications initialized with ng-app.

**Comment by wrozka** [comment]
It works both with `ng-app` and `data-ng-app`. Just use `0.1.0` version.
