### ISSUE TITLE
This project is not functional?

### ISSUE THREAD

**Issue by giovanicosta** [wrozka/capybara-angular#36]
I executed any tests with gem capybara-angular, but unsuccessfully! For example, why not find with <fill_in 'user.login', :with => 'teste'> ??? I tried find "ng-model" or "ng-click" directives using *fill_in* and *find*, but unsuccessfully. I inspected source code, but I did not find the functions. The capybara-angular is the project a skeleton?

**Comment by aaron-zipnosis** [comment]
That's not the purpose of this gem.  This waits for all angular events to be finished before executing capybara commands.
