### ISSUE TITLE
Warnings from Ruby 2.4

### ISSUE THREAD

**Issue by caboteria** [wrozka/capybara-angular#41]
We switched to Ruby 2.4 and now we're getting many warnings.  They mostly fall into two categories:
`/usr/local/bundle/gems/capybara-angular-0.2.6/lib/capybara/angular/dsl.rb:13: warning: instance variable @ignoring_angular not initialized`
and
`/usr/local/bundle/gems/capybara-angular-0.2.6/lib/capybara/angular.rb:10: warning: instance variable @default_max_wait_time not initialized`
They appear to be harmless but they happen often enough that it makes it hard to find legit log messages.

**Comment by mathieujobin** [comment]
2.4 is no longer supported.
