### ISSUE TITLE
Looking for a new maintainer?

### ISSUE THREAD

**Issue by mathieujobin** [wrozka/capybara-angular#43]
Hello,

I recently found out we still use this gem.

We have a monkey patch for ruby 3.0, and Rails 7
but its working fine for us... so no reason to replace it.

would you accept a patch and make a new release?

otherwise, if you can give me access to push releases to rubygems, I would fork and push directly to rubygems, I would hate having to rename.

I maintain many legacy gems such as this one. please have a look at my profile.

https://rubygems.org/profiles/mathieu

Thank you

**Comment by wrozka** [comment]
Hi @mathieujobin, thanks for reaching out. This is a great idea, I don't use this gem anymore, how should we proceed?

**Comment by wrozka** [comment]
I've just added you as a collaborator here and on rubygems, feel free to merge PRs and publish new versions. I'm happy to see that this gem is still being used.
